Gec/Controllers/Api/NewsController.cs
using Gec.EF.IRepo;
using Gec.Helpers.Gec.News;
using Gec.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gec.Controllers.Api
{
    
    [Route("/api/news")]
    public class NewsController : Controller
    {
        private ILogger<NewsController> _logger;
        private IFeedRepo _repo;

        public NewsController(IFeedRepo repo, ILogger<NewsController> logger)
        {
            _repo = repo;
            _logger = logger;
        }
        [HttpGet("")]
        public IActionResult Get()
        {
            try
            {
                //var result = _repo.GetTripsByUsername(this.User.Identity.Name);
                var allNewsVm = NewsMapper.ListNewsVM(_repo.GetAll("news").ToList());
                return Ok(allNewsVm);
            }
            catch (Exception ex)
            {
                // TODO LOGGING
                _logger.LogError($"Failed to get all news: {ex}");
                return BadRequest("Error occured");
            }
            //var news = _repo.GetAll("blog");
            //return Ok(news);
        }
        [HttpGet("{id}", Name = "NewsGet")]
        public IActionResult Get(int id)
        {
            try
            {
                var feed = _repo.Get(id);
                if (feed == null)
                {
                    return NotFound($"News {id} was not found");

                }
                else
                {
                    return Ok(feed);
                }
            }
            catch (Exception)
            {


            }
            return BadRequest();
        }
        [Authorize]
        [HttpPost("")]
        public async Task<IActionResult> Post([FromBody]NewsViewModel news)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    _logger.LogInformation("Creating a new News");
                    //ClaimsPrincipal currentUser = this.User;

                    var newNews = NewsMapper.newNews(news);

                    //newNews.User.UserName = User.Identity.Name;
                    _repo.Add(newNews);

                    if (await _repo.SaveChangesAsync())
                    {
                        var newUri = Url.Link("NewsGet", new { id = newNews.FeedId });
                        return Created(newUri, NewsMapper.NewsVM(newNews));
                        //return Created($"api/news/{newNews.FeedId}", NewsMapper.NewsVM(newNews));
                    }
                    else
                    {
                        _logger.LogWarning("Couldn't save news to the database");
                    }

                }
            }
            catch (Exception ex)
            {

                _logger.LogError($"Threw exception while saving News: {ex}");
                return BadRequest("Error ocurred");
            }

            return BadRequest("Failed to save the trip");
        }
        [HttpPatch("{id}")]
        [HttpPut("{id}")]
        [Authorize]
        public async Task<IActionResult> Put(int id, [FromBody] NewsViewModel news)
        {
            try
            {
                _logger.LogInformation($"Updating blog {news.Title}");
                var oldNews = _repo.Get(id);
                oldNews.Article = news.Article ?? oldNews.Article;
                oldNews.Title = news.Title ?? oldNews.Article;
                oldNews.Name = news.Name ?? oldNews.Name;
                oldNews.FeedType = news.FeedType ?? oldNews.FeedType;

                var updatedNews = _repo.Update(oldNews);
                if (await _repo.SaveChangesAsync())
                {
                    return Ok(updatedNews);
                }
            }
            catch (Exception ex)
            {

                _logger.LogError($"Threw exception updating blog: {ex}");
                return BadRequest("Could not update blog");
            }
            return BadRequest("Couldn't update Blog");
        }
        [Authorize]
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                _repo.Delete(id);
                if (await _repo.SaveChangesAsync())
                {
                    return Ok("News deleted");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Threw exception deleting news: {ex}");

            }
            return BadRequest("Could not delete News");
        }

    }
}

Gec/Controllers/Web/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gec.Controllers.Web
{
    public class BlogController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Blog()
        {
            return View();
        }
    }
}

Gec/Controllers/Web/GecController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Gec.ViewModels;
using Gec.Services;
using Microsoft.Extensions.Configuration;
using Gec.Models;
using Gec.EF;
using Gec.EF.Db;
using Gec.EF.IRepo;

namespace Gec.Controllers.Web
{
    
    public class GecController : Controller
    {
        IEmailService _emailService;
        IConfigurationRoot _config;
        IFeedRepo _feedRepo;

        public GecController(IEmailService emailService, IConfigurationRoot config, IFeedRepo feedRepo)
        {
            _emailService = emailService;
            _config = config;
            _feedRepo = feedRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Historia()
        {
            return View();
        }
        public IActionResult Contact()
        {            
            return View();
        }
        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com"))
                ModelState.AddModelError("Email", "We do not support AOL addresses");

            if (ModelState.IsValid)
            {
                _emailService.SendMeil(_config["MailSettings:ToAddress"], model.Email, "From Gec", model.Message);

                ModelState.Clear();

                ViewBag.UserMessage = "Message sent";
            }
                

            return View();
        }
    }
}

Gec/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gec</title>
    @*<title>@ViewBag.Title</title>*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    @*<link rel="stylesheet" href="~/lib/bootswatch/journal/bootstrap.min.css" />*@
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet">
    <link href="~/css/grid.css" rel="stylesheet" />
    <link href="~/css/master.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@

</head>
<body>
    <div class="container-fluid header">
        <div class="container">
            <div class="row">
                <div class="menublock">
                    <div class="col-sm-1 "></div>
                    <div class="col-sm-11 ">
                        <a asp-controller="Gec" asp-action="Index" class="topMenu">home</a>
                        <a asp-controller="News" asp-action="Index" class="topMenu">News</a>
                        <a asp-controller="Blog" asp-action="Index" class="topMenu">Blog</a>
                        <a asp-controller="Gec" asp-action="Historia" class="topMenu">Historia</a>
                        <a asp-controller="Gec" asp-action="Contact" class="topMenu">Contact</a>
                        <a asp-controller="Playground" asp-action="Index"  class="topMenu">Playground</a>

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="Account" asp-action="Login"  class="topMenu">Sign In <i class="fa fa-user-circle"></i></a>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="Account" asp-action="Logout"  class="topMenu"> Logout <i class="glyphicon glyphicon-log-out"></i></a>

                        }
                    </div>
                </div>
                <div class="row">
                    @*<div class="submenublock">
                        <div class="col-sm-1 "></div>
                        <div class="col-sm-11 ">
                            <a asp-controller="Playground" asp-action="Index" class="subtopMenu">Playground</a>

                            @if (!User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="Account" asp-action="Login" class="subtopMenu">Sign In <i class="fa fa-user-circle"></i></a>
                            }

                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="Account" asp-action="Logout" class="subtopMenu"> Logout <i class="glyphicon glyphicon-log-out"></i></a>

                            }
                            @*<a href="#" class="subtopMenu">Some link</a><a href="#" class="subtopMenu">Some link</a><a href="#" class="subtopMenu">Some link</a>*@
                        @*</div>
                    </div>*@
                </div>
                <!-- end menu -->
                <div class="row">
                    <div class="col-sm-2 "><img src="~/images/gec-logo.png" alt="Gec"></div>
                    <div class="col-sm-5  "></div>
                    <div class="col-sm-5 ">
                        <div class="row">
                            <div class="col-sm-12 headText1">Here we write about that wonderfull element about ugla some text</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 headText2">Ugla eyllow eyes vulgaris in lorem ipsum thesis lorem ipsum text</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end header -->
    @RenderBody()
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    @*<script type="text/javascript" src="~/js/site.js"></script>*@
    @RenderSection("scripts", false)
</body>
</html>

@*<body>
        <div id="sidebar">
            <div id="logo"><img alt="yo" src="~/img/gec.jpg" class="headshot" /></div>

            <ul class="nav">
                <li class="active"><a asp-controller="Gec" asp-action="Index">Noticias <i class="glyphicon glyphicon-globe"></i></a></li>
                <li><a asp-controller="Blog" asp-action="Index">Blog <i class="fa fa-newspaper-o"></i></a></li>
                <li><a asp-controller="Gec" asp-action="Historia">O Gec <i class="fa fa-leaf"></i></a></li>
                <li><a asp-controller="Playground" asp-action="Index">Playground <i class="fa fa-play-circle"></i></a></li>
                <li><a asp-controller="Gec" asp-action="Contact">Contacte <i class="glyphicon glyphicon-send"></i></a></li>

                @if (!User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Account" asp-action="Login">Sign in <i class="fa fa-user-circle"></i></a></li>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Account" asp-action="Logout">Sign out <i class="glyphicon glyphicon-log-out"></i></a></li>

                }
            </ul>
        </div>

        <div id="wrapper">
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <ul class="nav navbar-nav navbar">
                        <li>
                            <div id="buttonMenu">
                                <button id="sidebarToggle" class="btn btn-sm" type="button">
                                    <i class="fa fa-angle-left"></i>
                                </button>
                            </div>
                        </li>
                    </ul>
                    <a asp-controller="Playground" asp-action="Index" class="navbar-brand">gec</a>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="btn btn-sm btn-info"><i class="fa fa-save">Save</i></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="btn btn-sm btn-info"><i class="fa fa-print">Print</i></a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div id="main" class="container-fluid">
                <div>
                    @RenderBody();
                </div>
            </div>
            <div id="footer" class="container-fluid">
                <div class="navbar navbar-inverse navbar navbar-fixed-bottom">
                    <p>&copy; 2017 <a class="text-success" href="http://www.gec.pt">gec grupo ecológico de Cascais</a></p>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="~/js/site.js"></script>
        @RenderSection("scripts", false);

    </body>*@