Gec/Models/Playground/Stop.cs
using System;

namespace Gec.Models.Playground
{
    public class Stop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int Order { get; set; }
        public DateTime Arrival { get; set; }
    }
}

Gec/Models/Playground/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gec.Models.Playground
{
    public class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime DateCreated { get; set; }
        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }
    }
}

Gec/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gec.ViewModels
{
    public class TripViewModel
    {
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }
        public DateTime DateCreated { get; set; } = DateTime.UtcNow;
    }
}

Gec/Controllers/Api/TripsController.cs
 using Gec.EF.Repo;
using Gec.Models.Playground;
using Gec.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Gec.Helpers;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace Gec.Controllers.Api
{
    [Route("api/trips")]
    
    public class TripsController : Controller
    {
        private ILogger<TripsController> _logger;
        private IPlaygroundRepo _repo;

        public TripsController(IPlaygroundRepo repo, ILogger<TripsController> logger)
        {
           
            _repo = repo;
            _logger = logger;
        }
        //[HttpGet("api/trips")]
        //public JsonResult Get()
        //{
        //    return Json(new Trip() { Name = "My Trip" });
        //}

        /// <summary>
        /// Same but we can return a bad request
        /// </summary>
        /// <returns></returns>
        [HttpGet("")]
        public IActionResult Get()
        {
            try
            {
                var result = _repo.GetTripsByUsername(this.User.Identity.Name);
                var allTripsVm = Mappers.ListTripsVM(_repo.GetAllTrips().ToList());
                return Ok(allTripsVm);
            }
            catch (Exception ex)
            {
                // TODO LOGGING
                _logger.LogError($"Failed to get all trips: {ex}" );
                return BadRequest("Error occured");
            }
        }
        [HttpPost("")]
        public  async Task<IActionResult> Post([FromBody]TripViewModel trip)
        {
            if(ModelState.IsValid)
            {
                //ClaimsPrincipal currentUser = this.User;

                var newTrip = Mappers.newTrip(trip);

                newTrip.UserName = User.Identity.Name;
                _repo.Add(newTrip);

                if (await _repo.SaveChangesAsync())
                {
                    return Created($"api/trips/{trip.Name}", Mappers.TripVM(newTrip)); 
                }
                
            }
                
            return BadRequest("Failed to save the trip");
        }
    }
}

Gec/Controllers/Web/PlaygroundController.cs
using Gec.EF;
using Gec.EF.Db;
using Gec.EF.IRepo;
using Gec.EF.Repo;
using Gec.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gec.Controllers.Web
{
    public class PlaygroundController : Controller
    {
        IPlaygroundRepo _repo;
        IConfigurationRoot _config;
        ILogger<PlaygroundController> _logger;

        public PlaygroundController(IPlaygroundRepo repo, IConfigurationRoot config, ILogger<PlaygroundController> logger)
        {
            _repo = repo;
            _config = config;
            _logger = logger;
        }
        public IActionResult Index()
        {            
            return View();
        }
        [Authorize]
        public IActionResult Trips()
        {
            return View();
        //    try
        //    {
        //        var trips = _repo.GetAllTrips();
        //        return View(trips);
        //    }
        //    catch (Exception ex)
        //    {
        //        _logger.LogError($"Failed to get trips in Index page: {ex.Message}");
        //        return Redirect("/Error");
        //    }
        }
    }
}

Gec/Views/Playground/Index.cshtml
@model IEnumerable<Gec.Models.Playground.Trip>
@{
    ViewBag.Title = "Playground Page";

}
<div class="row">
    <div class="container">
        <div class="col-md-6">
            <a asp-controller="Playground" asp-action="Trips">
                <div class="thumbnail">
                    <img class="img-responsive" src="~/images/world.jpg" />
                </div>
            </a>
        </div>
    </div>
</div>

Gec/Views/Playground/Trips.cshtml
@section scripts {
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" type="text/javascript"></script>

    
    <script src="~/lib/gmaps/gmaps.min.js"></script>
    <script src="~/lib/travelmap/travelmap.min.js"></script>
    <script src="~/js/app-trips.js"></script>
    <script src="~/js/tripsController.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/tripEditorController.js"></script>
}
<div class="container">
    <div class="row" ng-app="app-trips">
        <div ng-view></div>       
    </div>
</div>